# ORIE 4580/5580/5581 Fall 2025

# **Recitation 1 - Intro to Python**

## Getting Started

In this course we will make use of python notebooks. We will demonstrate and support the use of Google Colab so that you don't have to worry about installing python and various libraries on your personal device. Though you are welcome to set up your own python environment on your device (e.g. using Anaconda), we may not be able to help you with some issues you may encounter.

Go to https://colab.research.google.com/ and sign in with a Google account. Then you can create a new notebook, open an existing notebook, or upload a notebook by clicking the "File" button in the top left of the window and choosing the respective option from the dropdown menu. For recitations, you may want to download the notebook from Canvas and then upload and open it in Google Colab so you can have your questions and answers next to each other. For homeworks you will likely create a new notebook from scratch.

Right under the "File" button are the "Code+" and "Text+" buttons. These let you add code cells and text cells respectively. Code cells are where you type your Python code and can run it by either clicking the play button that pops up on the left of the cell when you move your mouse over it or by clicking the cell and using the keyboard shortcut "Shift+Enter". The text cells let you add text/math in the notebook and is what allows us to display the text you're currently reading.

To save a notebook as a pdf to turn in (for homeworks or projects, no need to turn in for recitations), select "File" -> "Print" and then choose "Save as PDF" as the destination.



---



---



# Numpy Primer

You may be used to writing for loops in other classes but in python, iterating over lists (e.g. `[1,2,3]`) and operating on each element is very slow. One reason is that the objects in these lists can be of different types and sizes, for example `a = [1,'hello', (3,4,5), myObject]` is valid Python.

When working with numerical data, it's a good idea instead to use Numpy arrays where looping is done in optimized C code making use of vectorized operations. Consider two ways of applying a simple function to an array of numbers.

In [ ]:
# Importing Numpy
import numpy as np

# Importing Scipy (for PDFs and CDFs of distributions)
import scipy as sc

# Importing matplotlib for plotting
import matplotlib.pyplot as plt
%matplotlib inline

## Creating Numpy arrays

In [ ]:
# Creating an array with a range of values
arr_range = np.arange(0, 10, 2)  # Start, end, step

# Creating an array with a specified number of equally spaced values
arr_linspace = np.linspace(0, 1, 5)  # Start, end, number of values

# Creating an array of random values
arr_random = np.random.rand(3, 3)  # 3x3 random values between 0 and 1

# Creating an array with a specific shape and fill value
arr_zeros = np.zeros((2, 4))
arr_ones = np.ones((3, 2))

# Display the arrays
print("Range Array:", arr_range)
print("Linspace Array:", arr_linspace)
print("Random Array:", arr_random)
print("Zeros Array:", arr_zeros)
print("Ones Array:", arr_ones)

Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Array: [[0.73278832 0.68342314 0.73325622]
 [0.09833189 0.04530345 0.98935283]
 [0.84128983 0.65613431 0.87628556]]
Zeros Array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]]


### Practice exercises: Creating Arrays

1. Create a 1D array of even numbers from 10 to 50.
2. Create a 2D array of random integers between 1 and 100 with a shape of 4x5.
3. Create a 1D array of logarithmically spaced values between 0.1 and 1000 (inclusive).
4. Create a 3x3 identity matrix and multiply it by 5.

## Numpy is optimized for array operations

To make your code fast, you should get into a habit of using numpy functions and operations as much as possible for any mathematical task that you have, while on the other hand, minimizing looping over arrays. The following example demonstrates the difference in speeds of the same operation (computing the squares of the first $n$ whole numbers) using different methods.

In [ ]:
# Using for loops and lists
y = []
for i in range(20):
    y.append(i**2)
print(y)

# Using list comprehensions
y = [i**2 for i in range(20)]
print(y)

# Using numpy arrays
x = np.arange(20)
y = x**2
print(y)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]


We now use the [timeit cell magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit) command to compare these methods

In [ ]:
%%timeit
# Using for loops and lists
n = 20000
y = []
for i in range(n):
    y.append(i**2)

7.75 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
n = 20000
[i**2 for i in range(n)]

6.96 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
n = 20000
np.arange(n)**2

25.1 µs ± 6.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


By the way, why do you think the number of loops in the previous cases are different? You may find [this StackOverflow answer](https://stackoverflow.com/questions/48258008/n-and-r-arguments-to-ipythons-timeit-magic/59543135#59543135) interesting!

## Indexing and Slicing

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Indexing to get a single element
element12 = arr[1, 2]  # Row 1, Column 2

# Indexing to get element in last row and column
last_element = arr[-1, -1]  # Row 1, Column 2

# Slicing to get a subarray
subarray = arr[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2

# Display the results
print("Element[1,2]:", element12)
print("Last element:", last_element)
print("Subarray:")
print(subarray)

Element[1,2]: 6
Last element: 9
Subarray:
[[2 3]
 [5 6]]



Practice Exercises: Indexing and Slicing Arrays

1. Get the element at the center of the `arr` array.
2. Extract the last column of `arr`.
3. Slice the bottom-right 2x2 subarray of `arr`.
4. Create a new array containing the middle row of `arr`.

### Fancier indexing methods


In [ ]:
# Using fancy indexing to select specific elements
indices_row = np.array([0, 2])
indices_col = np.array([1, 2])
selected_elements = arr[indices_row, indices_col]

# Display the result
print("Selected Elements:")
print(selected_elements)


Selected Elements:
[2 9]



Practice Exercise:

1. Select elements at the corners of `arr`.


### Boolean (logical) indexing

In [ ]:
# Indexing and slicing
y = np.arange(10)**2
print(y[3:8])
mask = y > 5
print(mask)

# Indexing by boolean masks
print(y[mask])

[ 9 16 25 36 49]
[False False False  True  True  True  True  True  True  True]
[ 9 16 25 36 49 64 81]


Practice Exercises:

1. Use boolean indexing to select elements from `y` that are divisible by 3.
2. Create a boolean array indicating whether elements in `y` are even, then use it to extract the even elements.


### Multi-dimensional Array Operations

In [ ]:
# Creating 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
matrix_product = np.dot(arr1, arr2)

# Element-wise multiplication
element_wise_mult = arr1 * arr2

# Transpose of an array
arr1_transpose = arr1.T

# Display the results
print("Matrix Product:")
print(matrix_product)
print("Element-wise Multiplication:")
print(element_wise_mult)
print("Transpose of arr1:")
print(arr1_transpose)


Matrix Product:
[[19 22]
 [43 50]]
Element-wise Multiplication:
[[ 5 12]
 [21 32]]
Transpose of arr1:
[[1 3]
 [2 4]]


Practice Exercises
1. Divide `arr1` by a scalar value of `3`. Also try dividing by `3.0` (Python is sometimes loose about type conversion, so its important to know when it happens and when it does not)
2. Perform element-wise division between `arr2` and `arr1`.
3. Calculate the determinant of `arr1`.


### Intro to `numpy.random`

A workhorse for this course is the numpy.random package, which gives functions for sampling from various standard distributions. We see some examples below; get very used to looking up the [manual](https://numpy.org/doc/stable/reference/random/index.html) for this package to know exactly what each function does!


In [ ]:
# Generating a single random number between 0 and 1
rand_num = np.random.random()
print("Random Number between 0 and 1:", rand_num)

# Generating an array of random numbers between 0 and 1
rand_array = np.random.random(5)
print("Array of Random Numbers:", rand_array)

Random Number between 0 and 1: 0.5212067721811995
Array of Random Numbers: [0.27149617 0.62455712 0.74401334 0.61909806 0.42700555]


#### Sampling from different distributions


In [ ]:
# Generating random numbers from a uniform distribution
uniform_rand = np.random.uniform(low=0, high=10, size=5)
print("Uniform Random Numbers:", uniform_rand)

# Generating random numbers from a normal distribution
normal_rand = np.random.normal(loc=0, scale=1, size=5)
print("Normal Random Numbers:", normal_rand)

# Generating random numbers from a binomial distribution
binomial_rand = np.random.binomial(n=10, p=0.5, size=5)
print("Binomial Random Numbers:", binomial_rand)

# Generating random numbers from a Poisson distribution
poisson_rand = np.random.poisson(lam=3, size=5)
print("Poisson Random Numbers:", poisson_rand)

# Generating random numbers from an exponential distribution
exponential_rand = np.random.exponential(scale=2, size=5)
print("Exponential Random Numbers:", exponential_rand)

# Generating a 2D array with random values from a normal distribution
random_array = np.random.normal(loc=0, scale=1, size=(3, 3))
print("Random 2D Array:", random_array)

Uniform Random Numbers: [1.24711609 6.09941079 3.75738863 9.9330436  4.08383972]
Normal Random Numbers: [-0.77979299  0.23614888  0.75916381 -0.98874206  0.49427191]
Binomial Random Numbers: [5 6 6 6 3]
Poisson Random Numbers: [2 1 5 1 3]
Exponential Random Numbers: [1.90240498 2.18835587 4.27031882 4.29352232 4.12823405]
Random 2D Array: [[-0.96699597  0.59745887  1.22525779]
 [-0.22250387  0.49437983  1.60106342]
 [ 0.0938704   1.55652502 -0.50929182]]


### Basic Statistical Operations

Finally, we will see how to perform basic statistical operations on arrays - you will use these a lot this semester!

In [ ]:
# Creating a 1D array
data = np.random.randint(1,20,size=10)

# Mean and median
mean_data = np.mean(data)
median_data = np.median(data)

# Standard deviation and variance
std_data = np.std(data)
var_data = np.var(data)

# Max and min
max_data = np.max(data)
min_data = np.min(data)

# Display the results
print("Data:",data)
print("Mean:", mean_data)
print("Median:", median_data)
print("Standard Deviation:", std_data)
print("Variance:", var_data)
print("Maximum:", max_data)
print("Minimum:", min_data)

Data: [18  3  5  8  9  4  1 15 16 18]
Mean: 9.7
Median: 8.5
Standard Deviation: 6.197580172938467
Variance: 38.410000000000004
Maximum: 18
Minimum: 1


Practice Exercise:

1. Find the index of the maximum value in `arr`.
2. Calculate the 75th percentile of `arr`.
3. Calculate the correlation coefficient between two given arrays (recall how this was defined...)






---



---



## Question 1:  Saving the drunks

Suppose you are part of a paramedic team on foot assigned a $1$ mile stretch of the Las Vegas Strip for which you must respond to calls of drunk people needing medical attention. You and your team can walk at $1\text{mph}$ to respond to calls. Your section of the strip has a casino near the left end of it, thus you are more likely to respond to calls on the left side of your strip. Specifically, the location of your calls is distributed according to a $\text{Beta}(2,6)$ distribution.

You will eventually need to decide which location to choose as your base, where you wait to receive a call, to minimize your response time to the first call. You are also interested in the probability that you'll have to walk enough to work up a sweat to get to the first call from your base location.

a) Draw $1000$ samples from the $\text{Beta}(2,6)$ call location distribution and create a histogram of the samples with $20$ bins.

b) Plot the normalized histogram, by specifying density = True as an argument in the histogram function, on the same plot as the true pdf so that we can compare our histogram estimate of the pdf with the true pdf.

Hint: you can plot the histogram and pdf on top of eachother by using **plt.hist(...)** and **plt.plot(...)** for the pdf in seperate lines of code. You can also evaluate the pdf of a $\text{Beta}(\text{alpha},\text{beta})$ distribution at point $x$ by using **sc.stats.beta.pdf(x, alpha, beta)**.

c) Estimate the average response time for each base location ranging from $0, 0.01, 0.02, \ldots, 0.99, 1$ using $n=10000$ for each estimate and plot the estimates.

d) What was the smallest estimated average response time and what was the location of the base with the lowest value?

Hint: use **np.argmin(...)**

e) Estimate the probability that you will have to walk more than $0.2$ miles, and thus get sweaty, to get to the call when base location is $0.23$.

*Solution*

This probability is $P(|\text{call location} - 0.23|> 0.2)$

f) What is the true probability that you will have to walk more than $0.2$ miles to get to the call when base location is $0.23$?

Hint: You can evaluate the cdf of a $\text{Beta}(\text{alpha},\text{beta})$ distribution at point $x$ by using **sc.stats.beta.cdf(x, alpha, beta)**

*Solution*


(write answer here in markdown, and then use codebox to compute)

g) How does your absolute error of the estimated probability of having to walk more than $0.2$ miles with base location $0.23$ change as a function of $n$? Plot the error for a few values of $n$ between  10,000  and  1,000,000 .

*Solution*



## Question 2:   Using CDFs

In this question, we'll see how you can use CDFs to derive new distributions (and also practice numpy, plotting, etc).

Suppose random variables $X_{1}, X_{2}$ are i.i.d uniform random variables on $[0,1]$.  We define random variables $M_2 = \max (X_{1}, X_{2})$ as the maximum between each pair  of $X_{1}, X_{2}$.

a)  Let $n=1000$.  Generate $n$ samples of $M_2$:  $\hat M_2[1], \dots, \hat M_2[n]$.  Plot the samples using a histogram and 10 bins.  

*Solution:*

The histogram was found using simulating data.  We can also plot the EMPIRICAL cdf from our generated data.

b)  If the only thing we knew about our distribution is our sample $\hat M_2$, then we would assume that the probability of seeing the $j$-th largest value in $\hat M_2$ is $j/n$.  This forms the empirical cdf.

Plot the empirical cdf based on our sample $\hat M_2$ as a line graph.  What function does it remind you of?



The empirical cdf is generated from data, so it's not exact and changes slightly every time you generate a new sample.  The true cdf $F(x) = P(M_2 \leq x)$ has to be computed theoretically, and it's useful for learning about the distribution of $M_2$ and for computing things like expectation, variance, etc.


c)  Compute the cdf $F(x)$ and pdf $f(x)$ for $M_2$, as well as the expectation $E(M_2)$.  Compare the true cdf/pdf to the empirical cdf/pdf (plots) you generated above.



*Solution:*

(write answer in Markdown)

d)  Let $M_N = \max(X_1, \dots, X_N)$ where $X_i$ are i.i.d uniform variables on $(0,1)$.  Compute the cdf, pdf, and expectation of $M_N$.  Also compute the limit of $E(M_N)$ as $N \to \infty$.

*Solution:*



## Question 3: Central limit theorem and Monte Carlo methods in insurance

An insurance company serves five large customers. The insurance claim placed by each customer in a year is exponentially distributed with mean 200. Assume that the insurance claims from different customers are independent from each other.

a)  Estimate the probability that the total insurance claim placed by all customers in a year exceeds 900 by using the CLT approximation.

**Solution:**

Let $X_i$ be the value of the insurance claim placed by customer $i$ for $i = 1, \ldots, 5$. The CLT stipulates that, approximately,

\begin{align*}
 \frac{1}{5}\sum_{i=1}^5X_i \sim \mathcal{N}(\mu = 200, \sigma^2 = 200^2/5).
 \end{align*}
A sum of 900 or more over five customers corresponds to an average of 180 or more. Thus
\begin{align*}
 \mathbb{P}\left(\frac{1}{5}\sum_{i=1}^5 X_i > 180\right) \approx \mathbb{P}(\mathcal{N}(200,200^2/5)>180) =1-\Phi(-\sqrt{5}/10) = 0.588.
 \end{align*}

---

b)  Use 5,000 replications of a Monte Carlo simulation to estimate the probability that the total insurance claim placed by all customers in a year exceeds 900.

**Solution:**

---


c) Calculate the true probability that the total insurance claim placed by all customers in a year exceeds 900.

Hint: The sum of $k$ independent exponential random variables, each with mean $\beta$, follows an Erlang distribution with parameters $k$ and $\beta$ (note the second parameter in this case is called the scale parameter which is the parameterization scipy uses, alternatively some references define the second parameter to be the rate parameter, which is the reciprocal of the scale parameter).  This has a cdf of:
\begin{align*}
F(x) = 1 - \sum_{n=0}^{k-1} \frac{1}{n !} e^{-x/\beta} \left( \frac{x}{\beta} \right )^n.
\end{align*}

You may find the function sc.stats.erlang.cdf(x, a=$k$, loc$=0$, scale = $\beta$) useful in calculating your final answer as a decimal.

**Solution:**

The true probability that the total insurance claim placed by all customers in a year exceeds 900 is
\begin{align*}
\mathbb{P}(\text{Erlang}(k, \beta)>900) = \mathbb{P}(\text{Erlang}(5,200)>900)=1-F(900) = 0.5321.
\end{align*}

d)  Repeat parts (a), (b), and (c) to estimate (using CLT and Monte Carlo) and calculate (using Erlang) the probability that the total claim from 30 customers exceeds 5,400. How does the error of this CLT approximation compare to the error of the CLT approximation in part (a)?  Why do you think this is the case?

**Solution:**



Note that the error of the CLT approximation is lower than the one in part (a) (~0.016 instead of ~0.056) since we are now approximating the sum of a larger number of random quantities (30 instead of 5) as being normally distributed.

---



---


## Bonus Question
In this problem, you will use matrix multiplication to compute Fibbonacci numbers. Remember that the Fibonacci numbers are defined by the recurrence $ F_n  = F_{n-1} + F_{n-2}$ with the initial conditions (base cases) $ F_0=0, F_1=1$. We turn this $2$ term recurrence in to a $1$ term recurrence with vectors and matrices.
$$\begin{bmatrix} F_{n} \\F_{n-1} \end{bmatrix} = \begin{bmatrix}1 & 1\\1 & 0\end{bmatrix}\begin{bmatrix} F_{n-1} \\F_{n-2} \end{bmatrix}, \text{     with initial condition      }  \begin{bmatrix} F_{1} \\F_{0} \end{bmatrix} = \begin{bmatrix} 1 \\0 \end{bmatrix}$$

Take a moment to convince yourself that these two formulations are equivalent.

a) Write a python function that computes the $F_n$, using repeated multiplication by matrix $A$ from above.

b) While sequentially multiplying by the matrix above takes $O(n)$ time to compute $F_n$, it is possible to compute the matrix power $A^n$ all at once in only $O(\log(n))$ time by repeated squaring of the matrix. Conveniently, `np.linalg.matrix_power(A,n)` can do that for you. Write a new routine using the matrix powers and compare the runtime for large $n$ using `%timeit`